drop sequence gesss.GECM_SCAN_RUN_ID_S

CREATE Sequence gesss.GECM_SCAN_RUN_ID_S 
Increment By 1
Start With	 1000
NOMAXVALUE
NOCYCLE
NOCACHE;

CREATE Table gesss.gecm_UTF8_SCAN_HEADERS(SCAN_RUN_ID	Number Not null,
	   		 							  CREATION_DATE Date   )
 TABLESPACE GECUST
   PCTFREE 10   PCTUSED 40
   INITRANS 1   MAXTRANS 255
 STORAGE ( 
   INITIAL 40K NEXT 40K PCTINCREASE 50
   MINEXTENTS 1 MAXEXTENTS 505 )
   NOCACHE;

DROP TABLE gesss.GECM_UTF8_SCAN_ERRORS CASCADE CONSTRAINTS ; 

CREATE TABLE gesss.GECM_UTF8_SCAN_ERRORS (SCAN_RUN_ID	   Number NOT NULL,
  OBJ#		 	   Number,
  OWNER		       VARCHAR2(25), 
  TABLE_NAME  	   VARCHAR2 (50), 
  COLUMN_NAME      VARCHAR2 (50),
  GE_ROW_ID		   VARCHAR2 (30),
  SCAN_ERR#		   Number ,
  ORIGINAL_TEXT	   VARCHAR2 (2000),
  REVISED_TEXT	   VARCHAR2 (2000),
  STATUS_MESSAGE   VARCHAR2 (150),
  PROCESSED_FLAG   VARCHAR2 (1),
  UNSPSC_CODE	 Varchar2(25),
  processed_date Date,
  LANG			   VARCHAR2 (50),
  Creation_date    date,
  Created_by	   number,
  Last_update_date date,
  Last_updated_by  Number,
  REVISED_TEXT_WEISOP1	 	Varchar2(2000),
  REVISED_TEXT_WEISOP15	Varchar2(2000),
  REVISED_TEXT_WEISOWIN	Varchar2(2000),
  REVISED_TEXT_US7ASCII	Varchar2(2000),
  REVISED_TEXT_BK2UTF8		Varchar2(2000)) 
 TABLESPACE GECUST
   PCTFREE 10   PCTUSED 40
   INITRANS 1   MAXTRANS 255
 STORAGE ( 
   INITIAL 40K NEXT 40K PCTINCREASE 50
   MINEXTENTS 1 MAXEXTENTS 505 )
   NOCACHE;
   
   drop index GESSS.GECM_SCAN_ERRORS_U1
   
CREATE UNIQUE INDEX GESSS.GECM_SCAN_ERRORS_U1 on GESSS.GECM_UTF8_SCAN_ERRORS(SCAN_RUN_ID,GE_ROW_ID,TABLE_NAME,COLUMN_NAME,SCAN_ERR#)
 TABLESPACE GECUST
 STORAGE ( 
   INITIAL 40K NEXT 40K PCTINCREASE 50
   MINEXTENTS 1 MAXEXTENTS 505 );

CREATE TABLE gesss.GECM_UTF8_SCAN_ARCHIVE (SCAN_RUN_ID	   Number NOT NULL,
  OBJ#		 	   Number,
  OWNER		       VARCHAR2(25), 
  TABLE_NAME  	   VARCHAR2 (50), 
  COLUMN_NAME      VARCHAR2 (50),
  GE_ROW_ID		   VARCHAR2 (30),
  SCAN_ERR#		   Number ,
  ORIGINAL_TEXT	   VARCHAR2 (2000),
  REVISED_TEXT	   VARCHAR2 (2000),
  STATUS_MESSAGE   VARCHAR2 (150),
  PROCESSED_FLAG   VARCHAR2 (1),
  UNSPSC_CODE	 Varchar2(25),
  processed_date Date,
  LANG			   VARCHAR2 (50),
  Creation_date    date,
  Created_by	   number,
  Last_update_date date,
  Last_updated_by  Number,
  REVISED_TEXT_WEISOP1	 	Varchar2(2000),
  REVISED_TEXT_WEISOP15	Varchar2(2000),
  REVISED_TEXT_WEISOWIN	Varchar2(2000),
  REVISED_TEXT_US7ASCII	Varchar2(2000),
  REVISED_TEXT_BK2UTF8		Varchar2(2000)) 
 TABLESPACE GECUST
   PCTFREE 10   PCTUSED 40
   INITRANS 1   MAXTRANS 255
 STORAGE ( 
   INITIAL 40K NEXT 40K PCTINCREASE 50
   MINEXTENTS 1 MAXEXTENTS 505 )
   NOCACHE;

CREATE UNIQUE INDEX GESSS.GECM_SCAN_ARCHIVE_U1 on GESSS.GECM_UTF8_SCAN_ARCHIVE(SCAN_RUN_ID,GE_ROW_ID,TABLE_NAME,COLUMN_NAME,SCAN_ERR#)
 TABLESPACE GECUST
 STORAGE ( 
   INITIAL 40K NEXT 40K PCTINCREASE 50
   MINEXTENTS 1 MAXEXTENTS 505 );

DROP TABLE gesss.GECM_UTF8_SCAN_PARAMS CASCADE CONSTRAINTS ; 

CREATE TABLE gesss.GECM_UTF8_SCAN_PARAMS (
  SCAN_RUN_ID  Number Not Null, 
  NAME   VARCHAR2 (30)  NOT NULL, 
  VALUE  VARCHAR2 (80)  NOT NULL) 
 TABLESPACE GECUST
   PCTFREE 10   PCTUSED 40
   INITRANS 1   MAXTRANS 255
 STORAGE ( 
   INITIAL 128K NEXT 1024K PCTINCREASE 0
   MINEXTENTS 1 MAXEXTENTS 2000 )
   NOCACHE; 
   
   

DROP TABLE gesss.GECM_UTF8_INTERFACE_TL CASCADE CONSTRAINTS ; 

CREATE TABLE gesss.GECM_UTF8_INTERFACE_TL ( 
  TL_COL1   VARCHAR2 (150), 
  TL_COL2   VARCHAR2 (150), 
  TL_COL3   VARCHAR2 (150), 
  TL_COL4   VARCHAR2 (150), 
  TL_COL5   VARCHAR2 (150), 
  TL_COL6   VARCHAR2 (150), 
  TL_COL7   VARCHAR2 (150), 
  TL_COL8   VARCHAR2 (150), 
  TL_COL9   VARCHAR2 (150), 
  TL_COL10  VARCHAR2 (150), 
  TL_COL11  VARCHAR2 (150), 
  TL_COL12  VARCHAR2 (150), 
  TL_COL13  VARCHAR2 (150), 
  TL_COL14  VARCHAR2 (150), 
  TL_COL15  VARCHAR2 (150), 
  TL_COL16  VARCHAR2 (150), 
  TL_COL17  VARCHAR2 (150), 
  TL_COL18  VARCHAR2 (150), 
  TL_COL19  VARCHAR2 (150), 
  TL_COL20  VARCHAR2 (150), 
  TL_COL21  VARCHAR2 (150), 
  TL_COL22  VARCHAR2 (150), 
  TL_COL23  VARCHAR2 (150), 
  TL_COL24  VARCHAR2 (150), 
  TL_COL25  VARCHAR2 (150), 
  TL_COL26  VARCHAR2 (150), 
  TL_COL27  VARCHAR2 (150), 
  TL_COL28  VARCHAR2 (150), 
  TL_COL29  VARCHAR2 (150), 
  TL_COL30  VARCHAR2 (150)) 
 TABLESPACE GECUST
   PCTFREE 10   PCTUSED 40
   INITRANS 1   MAXTRANS 255
 STORAGE ( 
   INITIAL 40K NEXT 1024K PCTINCREASE 0
   MINEXTENTS 1 MAXEXTENTS 2147483645 )
   NOCACHE; 

GRANT ALTER ON gesss.GECM_UTF8_INTERFACE_TL TO APPS;

GRANT DELETE ON gesss.GECM_UTF8_INTERFACE_TL TO APPS;

GRANT INDEX ON gesss.GECM_UTF8_INTERFACE_TL TO APPS;

GRANT INSERT ON gesss.GECM_UTF8_INTERFACE_TL TO APPS;

GRANT SELECT ON gesss.GECM_UTF8_INTERFACE_TL TO APPS;

GRANT UPDATE ON gesss.GECM_UTF8_INTERFACE_TL TO APPS;

GRANT REFERENCES ON gesss.GECM_UTF8_INTERFACE_TL TO APPS;


Create or replace trigger GESSS.GECM_UTF8_SCAN_ERRORS_PDATE
      before insert or update of processed_flag ON gesss.gecm_utf8_Scan_errors
 for each row
 when (new.processed_flag is not null
       and new.processed_date is null)
 begin
  -- This trigger enforces that when the processed flag is set to something other than null that a date is entered. 
   :new.processed_date := sysdate;
 end;