




UPDATE GESSS.GECM_UTF8_SCAN_ERRORS X
SET X.PROCESSED_FLAG = 'I',
    X.REVISED_TEXT = (SELECT C.ITEM_DESCRIPTION--, A.*--c.po_header_id, c.segment1, c.ORG_ID, c.INTERFACE_SOURCE_CODE, c.creation_date,COUNT(a.po_line_id)
				    FROM PO.PO_LINES_ALL a
	 				    ,GESSS.GECM_UTF8_SCAN_ERRORS b
	 					,PO.PO_LINES_ALL@MJM_PROD.GE.COM c
					WHERE b.table_name = 'PO_LINES_ALL'
					AND b.ge_row_id = a.ROWID
					AND B.ROWID = X.ROWID
					AND	a.po_LINE_id = c.po_LINE_id)
WHERE X.TABLE_NAME = 'PO_LINES_ALL'
AND X.COLUMN_NAME = 'ITEM_DESCRIPTION'
AND X.REVISED_TEXT IS NULL

UPDATE GESSS.GECM_UTF8_SCAN_ERRORS X
SET X.PROCESSED_FLAG = 'I',
    X.REVISED_TEXT = (SELECT C.ITEM_DESCRIPTION--, A.*--c.po_header_id, c.segment1, c.ORG_ID, c.INTERFACE_SOURCE_CODE, c.creation_date,COUNT(a.po_line_id)
				    FROM PO.PO_LINES_ARCHIVE_ALL a
	 				    ,GESSS.GECM_UTF8_SCAN_ERRORS b
	 					,PO.PO_LINES_ALL@MJM_PROD.GE.COM c
					WHERE b.table_name = 'PO_LINES_ARCHIVE_ALL'
					AND b.ge_row_id = a.ROWID
					AND B.ROWID = X.ROWID
					AND	a.po_LINE_id = c.po_LINE_id)
WHERE X.TABLE_NAME = 'PO_LINES_ARCHIVE_ALL'
AND X.COLUMN_NAME = 'ITEM_DESCRIPTION'
AND X.REVISED_TEXT IS NULL

ROLLBACK

COMMIT

UPDATE GESSS.GECM_UTF8_SCAN_ERRORS X
SET X.PROCESSED_FLAG = 'I',
    X.REVISED_TEXT = (SELECT C.LAST_NAME--, A.*--c.po_header_id, c.segment1, c.ORG_ID, c.INTERFACE_SOURCE_CODE, c.creation_date,COUNT(a.po_line_id)
				    FROM PO.PO_VENDOR_CONTACTS a
	 				    ,GESSS.GECM_UTF8_SCAN_ERRORS b
	 					,PO.PO_VENDOR_CONTACTS@MJM_PROD.GE.COM c
					WHERE b.table_name = 'PO_VENDOR_CONTACTS'
					AND b.ge_row_id = a.ROWID
					AND B.ROWID = X.ROWID
					AND	a.VENDOR_CONTACT_id = c.VENDOR_CONTACT_id)
WHERE X.TABLE_NAME = 'PO_VENDOR_CONTACTS'


UPDATE GESSS.GECM_UTF8_SCAN_ERRORS X
SET X.PROCESSED_FLAG = 'I',
    X.REVISED_TEXT = (SELECT C.ITEM_DESCRIPTION--, A.*--c.po_header_id, c.segment1, c.ORG_ID, c.INTERFACE_SOURCE_CODE, c.creation_date,COUNT(a.po_line_id)
				    FROM PO.PO_LINES_INTERFACE a
	 				    ,GESSS.GECM_UTF8_SCAN_ERRORS b
	 					,PO.PO_LINES_INTERFACE@MJM_PROD.GE.COM c
					WHERE b.table_name = 'PO_LINES_INTERFACE'
					AND b.ge_row_id = a.ROWID
					AND B.ROWID = X.ROWID
					AND	a.po_LINE_id = c.po_LINE_id)
WHERE X.TABLE_NAME = 'PO_LINES_INTERFACE'
AND X.COLUMN_NAME = 'ITEM_DESCRIPTION'
AND X.REVISED_TEXT IS NULL

AND X.COLUMN_NAME = 'ITEM_DESCRIPTION'
AND X.REVISED_TEXT IS NULL



UPDATE GESSS.GECM_UTF8_SCAN_ERRORS X
SET X.PROCESSED_FLAG = 'I',
    X.REVISED_TEXT = (SELECT C.message_text--, A.*--c.po_header_id, c.segment1, c.ORG_ID, c.INTERFACE_SOURCE_CODE, c.creation_date,COUNT(a.po_line_id)
				    FROM applsys.FND_NEW_MESSAGES a
	 				    ,GESSS.GECM_UTF8_SCAN_ERRORS b
	 					,APPLSYS.FND_NEW_MESSAGES@MJM_PROD.GE.COM c
					WHERE b.table_name = 'FND_NEW_MESSAGES'
					AND b.ge_row_id = a.ROWID
					AND B.ROWID = X.ROWID
					AND a.application_id = c.application_id
					AND a.language_code = c.language_code
					AND a.MESSAGE_NUMBER = c.message_number
					AND   X.GE_ROW_ID = 'AADCkQAAVAAAVt3AAm')
WHERE X.TABLE_NAME = 'FND_NEW_MESSAGES'
AND   X.GE_ROW_ID = 'AADCkQAAVAAAVt3AAm'


ROLLBACK

UPDATE GESSS.GECM_UTF8_SCAN_ERRORS X
SET X.PROCESSED_FLAG = 'I',
    X.REVISED_TEXT = (SELECT C.CHECK_REQUEST_VENDOR--, A.*--c.po_header_id, c.segment1, c.ORG_ID, c.INTERFACE_SOURCE_CODE, c.creation_date,COUNT(a.po_line_id)
				    FROM GEMS.GEMS_DATAWAREHOUSE_TEMP_TABLE a
	 				    ,GESSS.GECM_UTF8_SCAN_ERRORS b
	 					,GEMS.GEMS_DATAWAREHOUSE_TEMP_TABLE@MJM_PROD.GE.COM c
					WHERE b.table_name = 'GEMS_DATAWAREHOUSE_TEMP_TABLE'
					AND b.ge_row_id = a.ROWID
					AND B.ROWID = X.ROWID
					AND	a.REQUISITION_NUMBER = c.REQUISITION_NUMBER)
WHERE X.TABLE_NAME = 'GEMS_DATAWAREHOUSE_TEMP_TABLE'

