DROP MATERIALIZED VIEW LOG ON JAROSODS.DEPARTMENT_MAS;
CREATE MATERIALIZED VIEW LOG ON JAROSODS.DEPARTMENT_MAS
TABLESPACE JAROSODSDAT
PCTUSED    99
PCTFREE    0
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          8M
            NEXT             8M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOCACHE
LOGGING
NOPARALLEL
WITH ROWID
INCLUDING NEW VALUES;

DROP MATERIALIZED VIEW LOG ON JAROSODS.LOOKUP_CODES_REF;
CREATE MATERIALIZED VIEW LOG ON JAROSODS.LOOKUP_CODES_REF
TABLESPACE JAROSODSDAT
PCTUSED    99
PCTFREE    0
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          8M
            NEXT             8M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOCACHE
LOGGING
NOPARALLEL
WITH ROWID
INCLUDING NEW VALUES;

DROP MATERIALIZED VIEW LOG ON JAROSODS.MFG_WIPOPREQUIREMENTS_DET;
CREATE MATERIALIZED VIEW LOG ON JAROSODS.MFG_WIPOPREQUIREMENTS_DET
TABLESPACE JAROSODSDAT
PCTUSED    99
PCTFREE    0
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          8M
            NEXT             8M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOCACHE
LOGGING
NOPARALLEL
WITH ROWID
INCLUDING NEW VALUES;

DROP MATERIALIZED VIEW LOG ON JAROSODS.PRODUCT_MAS;
CREATE MATERIALIZED VIEW LOG ON JAROSODS.PRODUCT_MAS
TABLESPACE JAROSODSDAT
PCTUSED    99
PCTFREE    0
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          8M
            NEXT             8M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOCACHE
LOGGING
NOPARALLEL
WITH ROWID
INCLUDING NEW VALUES;

DROP MATERIALIZED VIEW LOG ON JAROSODS.WAREHOUSE_MAS;
CREATE MATERIALIZED VIEW LOG ON JAROSODS.WAREHOUSE_MAS
TABLESPACE JAROSODSDAT
PCTUSED    99
PCTFREE    0
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          8M
            NEXT             8M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOCACHE
LOGGING
NOPARALLEL
WITH ROWID
INCLUDING NEW VALUES;

DROP MATERIALIZED VIEW LOG ON JAROSODS.WIP_ENTITY_MAS;
CREATE MATERIALIZED VIEW LOG ON JAROSODS.WIP_ENTITY_MAS
TABLESPACE JAROSODSDAT
PCTUSED    99
PCTFREE    0
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          8M
            NEXT             8M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOCACHE
LOGGING
NOPARALLEL
WITH ROWID
INCLUDING NEW VALUES;


EXECUTE DBMS_MVIEW.EXPLAIN_MVIEW ('GETS_DW_SVC.X_SVC_DW_WIP_JOBS_MTL_RQMTS_MV');